### ISSUE TITLE
Pixel Perfect Error

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#1]
4x KkthnxUI\Core\PixelPerfect.lua:69: attempt to perform arithmetic on global 'Mult' (a nil value)
KkthnxUI\Core\PixelPerfect.lua:69: in main chunk

Locals:
K = <unnamed> {
 TocVersion = 70000
 Color = <table> {
 }
 Class = "WARRIOR"
 ScreenHeight = 1440
 Resolution = "2560x1440"
 Race = "Gnome"
 WoWPatchReleaseDate = "Jul 22 2016"
 Level = 100
 Realm = "The Venture Co"
 WoWPatch = "7.0.3"
 ScreenWidth = 2560
 WoWBuild = "22293"
 Name = "Frackas"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 0 = <userdata>
 VersionNumber = 4.08
 Version = "4.08"
 Client = "enUS"
}
C = <table> {
 Nameplate = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Chat = <table> {
 }
 Loot = <table> {
 }
 Aura = <table> {
 }
 Skins = <table> {
 }
 PowerBar = <table> {
 }
 Filger = <table> {
 }
 Tooltip = <table> {
 }
 Minimap = <table> {
 }
 PulseCD = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 Bag = <table> {
 }
 Position = <table> {
 }
 ActionBar = <table> {
 }
 Automation = <table> {
 }
 Cooldown = <table> {
 }
 Error = <table> {
 }
}
_ = <table> {
}
format = <function> defined =[C]:-1
match = <function> defined =[C]:-1
select = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
min = <function> defined =[C]:-1
max = <function> defined =[C]:-1
CreateFrame = <function> defined =[C]:-1
GetCVar = <function> defined =[C]:-1
SetCVar = <function> defined =[C]:-1
NeedReloadUI = <function> defined @KkthnxUI\Core\PixelPerfect.lua:16
PixelPerfect = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 Combat_Font = "KkthnxUI\Media\Fonts\Damage.ttf"
 Glow = "KkthnxUI\Media\Textures\GlowTex.tga"
 Warning_Sound = "KkthnxUI\Media\Sounds\Warning.ogg"
 Backdrop_Color = <table> {
 }
 Overlay_Color = <table> {
 }
 Combat_Font_Size = 16
 Border_Glow = "KkthnxUI\Media\Border\Border_Glow.tga"
 Font_Style = "OUTLINE"
 Border_Color = <table> {
 }
 Proc_Sound = "KkthnxUI\Media\Sounds\Proc.ogg"
 Blank = "KkthnxUI\Media\Textures\Blank"
 Whisp_Sound = "KkthnxUI\Media\Sounds\Whisper.ogg"
 Blizz = "KkthnxUI\Media\Border\Border_Default.tga"
 Font = "KkthnxUI\Media\Fonts\Normal.ttf"
 Texture = "TargetingFrame\UI-StatusBar"
 Font_Size = 12
 Blank_Font = "KkthnxUI\Media\Fonts\Invisible.ttf"
 Combat_Font_Size_Style = "OUTLINE"
}
(*temporary) = 12
(*temporary) = nil
(*temporary) = <function> defined @KkthnxUI\Core\PixelPerfect.lua:32
(*temporary) = 54705
(*temporary) = "%d+x(%d+)"
(*temporary) = "attempt to perform arithmetic on global 'Mult' (a nil value)"

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/ad5b0f523fb76bf154325b2f1cb77edf1129a552
