### ISSUE TITLE
Currencies enhancement

### ISSUE THREAD

**Issue by EnumaElis** [Kkthnx/KkthnxUI_Legion#104]
I would like to see the equivalent functionality like https://mods.curse.com/addons/wow/elvui-legion-currencies in ElvUI
Does it possible in future?

**Comment by Kkthnx** [comment]
I will ping @Rav99 to look into this. He and I have been talking about data text lately

**Comment by Kkthnx** [comment]
Feature is present in https://github.com/Kkthnx/KkthnxUI_Legion/tree/6.10
