### ISSUE TITLE
blizzard raid frames

### ISSUE THREAD

**Issue by vortex250** [Kkthnx/KkthnxUI_Legion#106]
have deactivated custom raid frames and opted for default blizzard raid frames
upon invite they dont show till i /reload ui

i'd consider using the custom raid frames if you could somehow implement sorting of raid groups by "groups" with added labels identifying which group someone is in, this is how our raid leader sorts our groups out into doing certain tasks.

**Comment by Kkthnx** [comment]
Can you check with the latest 6.10 push on the 6.10 branch that this is fixed?

**Comment by vortex250** [comment]
wow you've put alot of effort into this new revision
and yes the blizzard raid frames now show when i get invited, so issue fixed

**Comment by Kkthnx** [comment]
Thank you.
