### ISSUE TITLE
mouseover buff 

### ISSUE THREAD

**Issue by ModernLobby** [Kkthnx/KkthnxUI_Legion#108]
This happens when i mouseover my buff :) 

Message: [string "KkthnxUIBuffHeaderAuraButton6:OnEnter"]:5: script ran too long
Time: 11/09/16 02:54:38
Count: 1
Stack: [string "*:OnEnter"]:5: in function <[string "*:OnEnter"]:1>

Locals: self = KkthnxUIBuffHeaderAuraButton6 {
 0 = <userdata>
 shadow = <unnamed> {
 }
 Dur = 8
 Duration = <unnamed> {
 }
 border = <unnamed> {
 }
 Count = <unnamed> {
 }
 Filter = "HELPFUL"
 Icon = <unnamed> {
 }
 TimeLeft = 6.4569999853265
}
motion = true
GameTooltip = GameTooltip {
 0 = <userdata>
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 IsSkinned = true
 SetSocketGem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.2
 SetInventoryItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 comparing = false
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 Hide = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = GameTooltip {
 0 = <userdata>
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 IsSkinned = true
 SetSocketGem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.2
 SetInventoryItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 comparing = false
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 Hide = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = "player"
(*temporary) = 6
(*temporary) = "HELPFUL"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"

**Comment by Kkthnx** [comment]
Was this buffs on the unit frames?

**Comment by ModernLobby** [comment]
Some DK Buff like Icy Talons but the thing is i can't replicate this error now :/

**Comment by Kkthnx** [comment]
Not able to reproduce this. 

@ModernLobby @peatah @AutoJames
If anyone one of you can reproduce this let me know and we will reopen 🗡
