### ISSUE TITLE
I get this whenever I log in

### ISSUE THREAD

**Issue by shiro545** [Kkthnx/KkthnxUI_Legion#109]
Message: Interface\AddOns\KkthnxUI\Core\Kill.lua:42: attempt to index global 'CompactRaidFrameManager' (a nil value)
Time: 11/09/16 10:20:44
Count: 1
Stack: Interface\AddOns\KkthnxUI\Core\Kill.lua:42: in function <Interface\AddOns\KkthnxUI\Core\Kill.lua:11>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to index global 'CompactRaidFrameManager' (a nil value)"
C = <table> {
 DataBars = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Bags = <table> {
 }
 Chat = <table> {
 }
 Partyframe = <table> {
 }
 Loot = <table> {
 }
 Automation = <table> {
 }
 Plugins = <table> {
 }
 WorldMapCoordinates = <table> {
 }
 filger_spells = <table> {
 }
 Filger = <table> {
 }
 Position = <table> {
 }
 Minimap = <table> {
 }
 Skins = <table> {
 }
 Tooltip = <table> {
 }
 PulseCD = <table> {
 }
 Raidframe = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 DataText = <table> {
 }
 WorldMap = <table> {
 }
 Nameplates = <table> {
 }
 ActionBar = <table> {
 }
 Cooldown = <table> {
 }
 Auras = <table> {
 }
}
hooksecurefunc = <function> defined =[C]:-1
K = <unnamed> {
 CreateShadowFrame = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:123
 AuraList = <table> {
 }
 RaidDebuffsReverse = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:41
 Scale = <function> defined @Interface\AddOns\KkthnxUI\Core\API.lua:25
 Race = "BloodElf"
 FormatMoney = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:239
 WindowedMode = true
 Realm = "Kazzak"
 SetShadowBorder = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:147
 WoWPatch = "7.1.0"
 UnitFrame_OnLeave = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:264
 ScreenWidth = 1920
 CheckChat = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:153
 UnusedTimers = <table> {
 }
 MultiCheck = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:54
 RaidDebuffsTracking = <table> {
 }
 Delay = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:310
 PetBarUpdate = <function> defined @Interface\AddOns\KkthnxUI\Modules\ActionBars\Functions.lua:73
 BorderBackdrop = <table> {
 }
 Color = <table> {
 }
 Class = "ROGUE"
 ScreenHeight = 1080
 ShortValue = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:58
 GetAddOnInfo = <function> defined @Interface\AddOns\KkthnxUI\Core\Init.lua:37
 DebuffBlackList = <table> {
 }
 CreateBlizzardFrame = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:99
 WoWPatchReleaseDate = "Nov  8 2016"
 AddAuras = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Elements\Auras.lua:243
 ShortenString = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:205
 NoScaleMult = 0.71111111111111
 PlateBlacklist = <table> {
 }
 CreateAuraWatchIcon = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:375
 Backdrop = <table> {
 }
 TexCoords = <table> {
 }
 NewTimer = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:302
 Name = "Ruîna"
 Noop = <function> defined @Interface\AddOns\KkthnxUI\Core\Init.lua:18
 RaidBuffsTrackingPosition = <table> {
 }
 ShadowBackdrop = <table> {
 }
 Comma = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:51
 Border = <table> {
 }
 CreateStatusBar = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:349
 Mult = 1.0015649452269
 Client = "enUS"
 CreateAuraWatch = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:390
 Role = "Melee"
 CreateBorder = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:128
 IsAddOnEnabled = <function> defined @Interface\AddOns\KkthnxUI\Core\Init.lua:49
 UploadDBM = <function> defined @Interface\AddOns\KkthnxUI\Modules\Skins\Addons\D

**Comment by Kkthnx** [comment]
Can't reproduce. Disable all your other addons expect KkthnxUI

**Comment by shiro545** [comment]
Looked around a bit for "compact raid frames" and found a config file in my characters saved variables folder for blizzard, this option was disabled. after i enabled it the popup didn't come
