### ISSUE TITLE
The problem with long names

### ISSUE THREAD

**Issue by Yuridemo** [Kkthnx/KkthnxUI_Legion#114]
If the item is not checked, an error occurs for long names (google translate :))
![wowscrnshot_121116_003826](https://cloud.githubusercontent.com/assets/24498421/21076048/29fb2dc0-bf3b-11e6-9694-2dac982e9b43.jpg)
![wowscrnshot_121116_003836](https://cloud.githubusercontent.com/assets/24498421/21076051/29fe4f00-bf3b-11e6-8611-b4693b5389de.jpg)
![wowscrnshot_121116_003846](https://cloud.githubusercontent.com/assets/24498421/21076049/29fbbb8c-bf3b-11e6-8365-bd5497c1c6b8.jpg)
![wowscrnshot_121116_003854](https://cloud.githubusercontent.com/assets/24498421/21076050/29fe1936-bf3b-11e6-977b-9db2b2b20a5c.jpg)

**Comment by Kkthnx** [comment]
Fixed. Thank you for your detailed report and for using my UI.
