### ISSUE TITLE
Unit frame issue

### ISSUE THREAD

**Issue by Yuridemo** [Kkthnx/KkthnxUI_Legion#115]
![wowscrnshot_121716_135432](https://cloud.githubusercontent.com/assets/24498421/21285985/5f82b3fc-c461-11e6-98ac-759786cfe8ab.png) 

Text of error:
//------------
Message: ...ce\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_GCD.lua:33: attempt to index global 'C' (a nil value)
Time: 12/17/16 13:53:15
Count: 1
Stack: ...ce\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_GCD.lua:33: in function `enable'
Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:98: in function `EnableElement'
Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:270: in function <Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:193>
(tail call): ?
Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:560: in function `Spawn'
...ddOns\KkthnxUI\Modules\Unitframes\Layouts\Layout.lua:976: in main chunk

Locals: self = oUF_KkthnxPlayer {
 IsMainFrame = true
 MasterLooter = <unnamed> {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <table> {
 }
 Leader = <unnamed> {
 }
 mouseovers = <table> {
 }
 Resting = <unnamed> {
 }
 GCD = oUF_KkthnxPlayer_GCD {
 }
 CCastbar = oUF_KkthnxPlayerCastbar {
 }
 PvPTimer = <unnamed> {
 }
 __elements = <table> {
 }
 Texture = <unnamed> {
 }
 PowerPrediction = <table> {
 }
 Power = <unnamed> {
 }
 DruidMana = <unnamed> {
 }
 ThreatGlow = <unnamed> {
 }
 Health = <unnamed> {
 }
 UNIT_EXITED_VEHICLE = <table> {
 }
 Portrait = <unnamed> {
 }
 unit = "player"
 GROUP_ROSTER_UPDATE = <table> {
 }
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\leader.lua:53
 PARTY_LOOT_METHOD_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\masterlooter.lua:73
 PortraitTimer = <unnamed> {
 }
 OfflineIcon = <unnamed> {
 }
 PvP = <unnamed> {
 }
 CFade = <table> {
 }
 UNIT_EXITING_VEHICLE = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Layouts\Layout.lua:260
 LFDRole = <unnamed> {
 }
 ReadyCheck = <unnamed> {
 }
 AdditionalPower = <unnamed> {
 }
 Combat = <unnamed> {
 }
 0 = <userdata>
 IsTargetFrame = false
 HealPrediction = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:148
 UNIT_ENTERING_VEHICLE = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Layouts\Layout.lua:260
 cUnit = "player"
 Name = <unnamed> {
 }
 PhaseIcon = <unnamed> {
 }
 Level = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 CombatFeedbackText = <unnamed> {
 }
 style = "oUF_Kkthnx"
}
bar = oUF_KkthnxPlayer_GCD {
 0 = <userdata>
 spark = <unnamed> {
 }
 Height = 4
 Color = <table> {
 }
 Width = 8
}
width = 116.00000762939
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "DIALOG"
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C' (a nil value)"
GetTime = <function> defined =[C]:-1
starttime = nil
duration = nil
spells = <table> {
 DEATHKNIGHT = 48266
 WARRIOR = 34428
 PALADIN = 35395
 MAGE = 44614
 PRIEST = 585
 SHAMAN = 403
 WARLOCK = 686
 DEMONHUNTER = 204157
 ROGUE = 1752
 DRUID = 5176
 MONK = 100780
 HUNTER = 3044
}
MyClass = "DRUID"
spellid = nil
usingspell = nil

**Comment by Yuridemo** [comment]
Q: Can I change the order of action panels?

**Comment by Kkthnx** [comment]
Currently no.
