### ISSUE TITLE
ошибка при открытии правой кнопки по полосе чести  книги с выбором срециализации

### ISSUE THREAD

**Issue by Kyman81** [Kkthnx/KkthnxUI_Legion#116]
![wowscrnshot_121816_061507](https://cloud.githubusercontent.com/assets/24628925/21290654/6cbc8dd6-c4ed-11e6-9fb3-68569482c706.jpg)

**Comment by Kyman81** [comment]
Message: ...erface\AddOns\KkthnxUI\Modules\DataBars\HonorBar.lua:68: attempt to call upvalue 'PlayerTalentTab_OnClick' (a nil value)
Time: 12/18/16 06:50:31
Count: 7
Stack: ...erface\AddOns\KkthnxUI\Modules\DataBars\HonorBar.lua:68: in function <...erface\AddOns\KkthnxUI\Modules\DataBars\HonorBar.lua:51>

Locals: self = <unnamed> {
 SetBorderTexture = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:54
 SetBorderPadding = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:90
 SetBorderSize = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:68
 SetBorderColor = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:29
 borderShadow = <table> {
 }
 SetBorderShadowColor = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:41
 GetBorderSize = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:83
 SetBackdropBorderColor = <function> defined @Interface\AddOns\KkthnxUI\Core\Border.lua:16
 borderTextures = <table> {
 }
 0 = <userdata>
}
button = "RightButton"
(*temporary) = nil
(*temporary) = PlayerTalentFrameTab3 {
 0 = <userdata>
}
(*temporary) = "attempt to call upvalue 'PlayerTalentTab_OnClick' (a nil value)"
LoadAddOn = <function> defined =[C]:-1
TogglePVPUI = <function> defined @Interface\FrameXML\UIParent.lua:841
ShowUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2856
PlayerTalentTab_OnClick = nil
_G = <table> {
 VUHDO_I18N_SYMBOL = "Символ"
 ERR_OUT_OF_CHI = "Недостаточно ци"
 DH_HAVOC_CORE_ABILITY_2 = "Мощная атака ближнего боя, расходующая гнев. Возмещает затраты гнева, если наносит критический урон."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Цветовое выделение названий объектов."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 734
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "Этот кутила хочет потанцевать с вами."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 395
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Сумки, являющиеся частью экипировки, не продаются и не покупаются."
 VuhDoNewOptionsPanelTextBarTextPanelMonoCheckButtonTextureActiveSwatch = VuhDoNewOptionsPanelTextBarTextPanelMonoCheckButtonTextureActiveSwatch {
 }
 PVP_RANK_6_1 = "Капрал"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 ClassHallTalentInset = ClassHallTalentInset {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Способности будут задействоваться, когда пользователь нажимает, а не отпускает клавишу."
 BINDING_NAME_NAMEPLATES = "Показать индикаторы врагов"
 CHAT_HEADER_SUFFIX = ": "
 Atr_StackList9 = Atr_StackList9 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Щелкните здесь, чтобы сделать
копию этого письма."
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Зал Чернорука"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2344
 TutorialFrameRight19 = Tuto

**Comment by Kkthnx** [comment]
Let me know if this is fixed. Thank you.

**Comment by Kkthnx** [comment]
@Kyman81 If you use discord please join in on our discord for the UI. We have a lot of people that come in over 100 and you are welcome to hang out.

https://discord.gg/Kjyebkf
