### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Kyman81** [Kkthnx/KkthnxUI_Legion#117]
Message: ...Ons\KkthnxUI\Modules\DataText\Elements\OrderHall.lua:67: bad argument #1 to 'format' (string expected, got nil)
Time: 12/21/16 13:50:01
Count: 15
Stack: [C]: ?
...Ons\KkthnxUI\Modules\DataText\Elements\OrderHall.lua:67: in function <...Ons\KkthnxUI\Modules\DataText\Elements\OrderHall.lua:47>

Locals: (*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = "string expected, got nil"

**Comment by Kkthnx** [comment]
Already fixed on my end. Will upload today.
