### ISSUE TITLE
LUA Error, dont know why

### ISSUE THREAD

**Issue by Javox9** [Kkthnx/KkthnxUI_Legion#118]
Message: Interface\AddOns\KkthnxUI\Core\Animation.lua:23: attempt to call method 'CreateAnimationGroup' (a nil value)
Time: 12/26/16 02:06:55
Count: 1374
Stack: Interface\AddOns\KkthnxUI\Core\Animation.lua:23: in function `SetUpAnimGroup'
Interface\AddOns\KkthnxUI\Core\Animation.lua:66: in function `Flash'
...e\AddOns\KkthnxUI\Modules\DataText\Elements\Time.lua:180: in function <...e\AddOns\KkthnxUI\Modules\DataText\Elements\Time.lua:174>

Locals: object = <table> {
 CreateShadowFrame = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:144
 AuraList = <table> {
 }
 SlideIn = <function> defined @Interface\AddOns\KkthnxUI\Core\Animation.lua:84
 SetFontString = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:59
 Scale = <function> defined @Interface\AddOns\KkthnxUI\Core\API.lua:26
 CheckAddOn = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:115
 ErrorBlackList = <table> {
 }
 FormatMoney = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:220
 UIFrameFade_OnUpdate = <function> defined @Interface\AddOns\KkthnxUI\Core\Animation.lua:109
 Realm = "Dun Modr"
 SetShadowBorder = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:168
 WoWPatch = "7.1.0"
 UnitFrame_OnLeave = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:234
 BorderBackdropTwo = <table> {
 }
 CheckChat = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:174
 UnusedTimers = <table> {
 }
 MultiCheck = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:66
 RaidDebuffsTracking = <table> {
 }
 Delay = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:347
 PetBarUpdate = <function> defined @Interface\AddOns\KkthnxUI\Modules\ActionBars\Functions.lua:67
 PriestColors = <table> {
 }
 FullscreenMode = true
 SetUpAnimGroup = <function> defined @Interface\AddOns\KkthnxUI\Core\Animation.lua:8
 Class = "DEATHKNIGHT"
 ScreenHeight = 1080
 ShortValue = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:75
 DebuffBlackList = <table> {
 }
 CreateBlizzardFrame = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:120
 WoWPatchReleaseDate = "Dec  9 2016"
 KillMenuOption = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:259
 NoScaleMult = 0.71111111111111
 PlateBlacklist = <table> {
 }
 CustomCastDelayText = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:516
 WindowedMode = true
 MerchantFilter = <table> {
 }
 CreateAuraWatchIcon = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:280
 PostUpdateHealth = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:133
 Backdrop = <table> {
 }
 tDeleteItem = <function> defined @Interface\AddOns\KkthnxUI\Core\Animation.lua:211
 TutorialList = <table> {
 }
 NewTimer = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:337
 Name = "Jagolux"
 ErrorWhiteList = <table> {
 }
 RaidBuffsTrackingPosition = <table> {
 }
 Auras = <unnamed> {
 }
 StylePet = <function> defined @Interface\AddOns\KkthnxUI\Modules\ActionBars\Style.lua:189
 BorderBackdrop = <table> {
 }
 HideSpiral = <function> defined @Interface\AddOns\KkthnxUI\Modules\ActionBars\Hide.lua:165
 ShadowBackdrop = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\KkthnxUI\Modules\ActionBars\Functions.lua:29
 CustomAuraFilters = <table> {
 }
 Comma = <function> defined @Interface\AddOns\KkthnxUI\Core\Functions.lua:69
 CustomCastTimeText = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:512
 Border = <table> {
 }
 Flash = <function> defined @Interface\AddOns\KkthnxUI\Core\Animation.lua:64
 CreateStatusBar = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Functions.lua:254
 Mult = 1.0015649452269
 CheckRole = <function> defined @Interface\AddOns\KkthnxUI\Core\Constants.lua:23
 UIFrameFadeIn = <function> defined @Interface\AddOns\Kkthnx

**Comment by Kkthnx** [comment]
Fixed https://github.com/Kkthnx/KkthnxUI_Legion/commit/e4ac4e44835533df40560c9f18aeeaee8c01893c
