### ISSUE TITLE
Castbar timer

### ISSUE THREAD

**Issue by L3n1n** [Kkthnx/KkthnxUI_Legion#13]
Castbar timer does not work only for me?

![](http://i.imgur.com/bMnvZbS.jpgg)

**Comment by Kkthnx** [comment]
Half fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/49922c9c9914b3ce9f5c80a32001caa1c219c2a5

The target cast bar still doesn't work. I'm going to go eat and think on
it. They were working not long ago IDK what blizzard has changed to
cause this.

**Comment by Kkthnx** [comment]
Oh god I see my own issue now lol. Pushing a fix in a bit.

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/4c8bbd66c2d4da74b8b9da18aa4a2b82ae8977e7
