### ISSUE TITLE
No ExtraActionButton

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#14]
No button for ExtraActionButton (Unless I'm blind) so things like planting bombs in Strand is impossible.

**Comment by Kkthnx** [comment]
Will have this fixed today :D

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/c8e3651afdca711aa494b3ab9a8891984a66e246
