### ISSUE TITLE
Protected function 'Boss2TargetFrame

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#15]
1x [ADDON_ACTION_BLOCKED] AddOn 'KkthnxUI' tried to call the protected function 'Boss2TargetFrame:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\TargetFrame.lua:109: in function `TargetFrame_Update'
FrameXML\TargetFrame.lua:175: in function `OnEvent'
FrameXML\UnitFrame.lua:917: in function <FrameXML\UnitFrame.lua:915>

Locals:

**Comment by Kkthnx** [comment]
Grr. I really need to just move to oUF. Ill look into this.
