### ISSUE TITLE
Attempt to call method 'FadeIn' and 'FadeOut'

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#16]
1x KkthnxUI\Modules\ActionBars\Toggle.lua:342: attempt to call method 'FadeIn' (a nil value)
KkthnxUI\Modules\ActionBars\Toggle.lua:342: in function <KkthnxUI\Modules\ActionBars\Toggle.lua:337>

Locals:
(*temporary) = nil
(*temporary) = ToggleBar3 {
 0 = <userdata>
 Text = <unnamed> {
 }
 backdrop = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'FadeIn' (a nil value)"
i = 3
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Comma = <function> defined @KkthnxUI\Core\Functions.lua:46
 Border = <table> {
 }
 Mult = 0.86021505376344
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:52
 White_List = <table> {
 }
 Client = "enUS"
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:11
 WoWBuild = "22345"
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:116
 TexCoords = <table> {
 }
 WoWPatch = "7.0.3"
 UploadDBM = <function> defined @KkthnxUI\Modules\Skins\Addons\DBM.lua:264
 ScreenWidth = 2480
 StylePet = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:150
 MoverFrames = <table> {
 }
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:98
 PixelBorder = <table> {
 }
 UIFrameFadeRemoveFrame = <function> defined @KkthnxUI\Core\Animation.lua:128
 ShiftBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:5
 UIFrameFadeOut = <function> defined @KkthnxUI\Core\Animation.lua:107
 CreateBorder = <function> defined @KkthnxUI\Core\Border.lua:80
 VersionNumber = 5.02
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:247
 PetBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:43
 TocVersion = 70000
 NeedLoot = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "WARRIOR"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "2480x1395"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:67
 Role = "Tank"
 UIFrameFadeIn = <function> defined @KkthnxUI\Core\Animation.lua:97
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:234
 WoWPatchReleaseDate = "Aug  1 2016"
 Level = 100
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:149
 NoScaleMult = 0.5505376344086
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\Core\Functions.lua:90
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:211
 TimeColors = <table> {
 }
 ComboColor = <table> {
 }
 RuneColor = <table> {
 }
 Backdrop = <table> {
 }
 UIParent = KkthnxUIParent {
 }
 Round = <function> defined @KkthnxUI\Core\Functions.lua:81
 ScreenHeight = 1395
 Version = "5.02"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 Race = "Gnome"
 StyleShift = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:140
 Realm = "The Venture Co"
 Name = "Frackas"
}
ToggleBar = ToggleActionbar {
 1 = ToggleBar1 {
 }
 2 = ToggleBar2 {
 }
 3 = ToggleBar3 {
 }
 4 = ToggleBar4 {
 }
 5 = ToggleBar5 {
 }
 0 = <userdata>
}
C = <table> {
 Nameplate = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Chat = <table> {
 }
 Loot = <table> {
 }
 Aura = <table> {
 }
 Skins = <table> {
 }
 PowerBar = <table> {
 }
 Filger = <table> {
 }
 filger_spells = <table> {
 }
 Tooltip = <table> {
 }
 Minimap = <table> {
 }
 PulseCD = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 Bag = <table> {
 }
 Position = <table> {
 }
 ActionBar = <table> {
 }
 Automation = <table> {
 }
 Cooldown = <table> {
 }
 Error = <table> {
 }
}

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/42410eac93a409ccbcac08beaa78757b8f8dab9d
