### ISSUE TITLE
SellGreyRepair

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#17]
2x ...ddOns\KkthnxUI\Modules\Automation\SellGreyRepair.lua:51: attempt to call upvalue 'GetNumPartyMembers' (a nil value)
...ddOns\KkthnxUI\Modules\Automation\SellGreyRepair.lua:51: in function <...ddOns\KkthnxUI\Modules\Automation\SellGreyRepair.lua:24>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "MERCHANT_SHOW"
cost = 401692
needed = true
GuildWealth = true
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetNumPartyMembers' (a nil value)"
GetContainerNumSlots = <function> defined =[C]:-1
GetContainerItemLink = <function> defined =[C]:-1
select = <function> defined =[C]:-1
GetItemInfo = <function> defined =[C]:-1
GetItemCount = <function> defined =[C]:-1
UseContainerItem = <function> defined =[C]:-1
itemCount = 0
sellValue = 0
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Comma = <function> defined @KkthnxUI\Core\Functions.lua:46
 Border = <table> {
 }
 Mult = 0.85898353614889
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:52
 White_List = <table> {
 }
 Client = "enUS"
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:11
 WoWBuild = "22345"
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:116
 TexCoords = <table> {
 }
 WoWPatch = "7.0.3"
 UploadDBM = <function> defined @KkthnxUI\Modules\Skins\Addons\DBM.lua:264
 ScreenWidth = 2483
 StylePet = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:150
 MoverFrames = <table> {
 }
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:98
 PixelBorder = <table> {
 }
 UIFrameFadeRemoveFrame = <function> defined @KkthnxUI\Core\Animation.lua:128
 ShiftBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:5
 UIFrameFadeOut = <function> defined @KkthnxUI\Core\Animation.lua:107
 CreateBorder = <function> defined @KkthnxUI\Core\Border.lua:80
 VersionNumber = 5.03
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:247
 PetBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:43
 TocVersion = 70000
 NeedLoot = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "WARRIOR"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "2483x1397"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:67
 Role = "Tank"
 UIFrameFadeIn = <function> defined @KkthnxUI\Core\Animation.lua:97
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:234
 WoWPatchReleaseDate = "Aug  1 2016"
 Level = 100
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:149
 NoScaleMult = 0.54974946313529
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\Core\Functions.lua:90
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:211
 TimeColors = <table> {
 }
 ComboColor = <table> {
 }
 RuneColor = <table> {
 }
 Backdrop = <table> {
 }
 UIParent = KkthnxUIParent {
 }
 Round = <function> defined @KkthnxUI\Core\Functions.lua:81
 ScreenHeight = 1397
 Version = "5.03"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 Race = "Gnome"
 StyleShift = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:140
 Realm = "The Venture Co"
 Name = "Frackas"
}
format = <function> defined =[C]:-1
CanMerchantRepair = <function> defined =[C]:-1
GetRepairAllCost = <function> defined =[C]:-1
CanGuildBankRepair = <function> defined =[C]:-1
GetGuildBankWithdrawMoney = <function> defined =[C]:-1
GetNumPartyMembers = nil
RepairAllItems = <function> defined =[C]:-1
GetMoney = <function> defined =[C]:-1

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/be9af1de59805aceec8f4042782f8074f0b23ada
