### ISSUE TITLE
Already Known Toggle

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#2]
I have a few more issues to post but I'll refrain until I get the okay I'm adding these correctly. 

1x KkthnxUI\Modules\Misc\AlreadyKnown.lua:29: attempt to call global 'GetAuctionItemClasses' (a nil value)
KkthnxUI\Modules\Misc\AlreadyKnown.lua:29: in main chunk

Locals:
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Comma = <function> defined @KkthnxUI\Core\Functions.lua:46
 Border = <table> {
 }
 Unit = "Player-163-08A86FF4"
 Mult = 0.83333333333333
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:52
 White_List = <table> {
 }
 Client = "enUS"
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:11
 WoWBuild = "22293"
 WoWPatch = "7.0.3"
 ScreenWidth = 2560
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:98
 PixelBorder = <table> {
 }
 UIFrameFadeOut = <function> defined @KkthnxUI\Core\Animation.lua:107
 VersionNumber = 4.08
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:247
 CreateBorder = <function> defined @KkthnxUI\Core\Border.lua:80
 TocVersion = 70000
 TimeColors = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "WARRIOR"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "2560x1440"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:67
 UIFrameFadeRemoveFrame = <function> defined @KkthnxUI\Core\Animation.lua:128
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:116
 UIFrameFadeIn = <function> defined @KkthnxUI\Core\Animation.lua:97
 WoWPatchReleaseDate = "Jul 22 2016"
 Level = 100
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:149
 NoScaleMult = 0.53333333333333
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\Core\Functions.lua:90
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:234
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:211
 ComboColor = <table> {
 }
 RuneColor = <table> {
 }
 Backdrop = <table> {
 }
 UIParent = KkthnxUIParent {
 }
 Round = <function> defined @KkthnxUI\Core\Functions.lua:81
 ScreenHeight = 1440
 Version = "4.08"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 Race = "Gnome"
 TexCoords = <table> {
 }
 Realm = "The Venture Co"
 Name = "Frackas"
}
C = <table> {
 Nameplate = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Chat = <table> {
 }
 Loot = <table> {
 }
 Aura = <table> {
 }
 Skins = <table> {
 }
 PowerBar = <table> {
 }
 Filger = <table> {
 }
 filger_spells = <table> {
 }
 Tooltip = <table> {
 }
 Minimap = <table> {
 }
 PulseCD = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 Bag = <table> {
 }
 Position = <table> {
 }
 ActionBar = <table> {
 }
 Automation = <table> {
 }
 Cooldown = <table> {
 }
 Error = <table> {
 }
}
L = <table> {
}
_ = <table> {
}
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 736
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 395
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK

**Comment by Kkthnx** [comment]
You are adding them fine. :D Thank you very much for taking the time to use my UI and post this bugs.

**Comment by jenderle7** [comment]
No problem! This is my favorite UI :D Keep up the good work!

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/ad5b0f523fb76bf154325b2f1cb77edf1129a552
