### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI_Legion#20]
![wowscrnshot_1111](https://cloud.githubusercontent.com/assets/20854352/17429058/48e0568e-5af5-11e6-86b7-e473c73e5ab1.jpg)

**Comment by Kkthnx** [comment]
Will have a fix in a few hours.

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/c0d5846dbe7bdc81ead48d29b580b741e0d18519
