### ISSUE TITLE
addon Mapster

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI_Legion#23]
`1x KkthnxUI\Core\Disable-Отключить.lua:64: attempt to index field 'map' (a nil value)
KkthnxUI\Core\Disable-Отключить.lua:64: in main chunk

Locals:
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Comma = <function> defined @KkthnxUI\Core\Functions.lua:46
 Border = <table> {
 }
 Unit = "Player-1602-097C8BF7"
 Mult = 1
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:52
 White_List = <table> {
 }
 Client = "ruRU"
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:11
 WoWBuild = "22396"
 WoWPatch = "7.0.3"
 ScreenWidth = 1440
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:98
 PixelBorder = <table> {
 }
 UIFrameFadeOut = <function> defined @KkthnxUI\Core\Animation.lua:107
 VersionNumber = 5.04
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:247
 TocVersion = 70000
 TimeColors = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "ROGUE"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "1440x900"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:67
 UIFrameFadeRemoveFrame = <function> defined @KkthnxUI\Core\Animation.lua:128
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:116
 UIFrameFadeIn = <function> defined @KkthnxUI\Core\Animation.lua:97
 WoWPatchReleaseDate = "Aug  8 2016"
 Level = 63
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:149
 NoScaleMult = 0.85333333333333
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\Core\Functions.lua:90
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:234
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:211
 ComboColor = <table> {
 }
 RuneColor = <table> {
 }
 Backdrop = <table> {
 }
 UIParent = KkthnxUIParent {
 }
 Round = <function> defined @KkthnxUI\Core\Functions.lua:81
 ScreenHeight = 900
 Version = "5.04"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 Race = "BloodElf"
 TexCoords = <table> {
 }
 Realm = "Гордунни"
 Name = "Блудзагул"
}
C = <table> {
 Nameplate = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Chat = <table> {
 }
 Loot = <table> {
 }
 Aura = <table> {
 }
 Skins = <table> {
 }
 PowerBar = <table> {
 }
 Filger = <table> {
 }
 Tooltip = <table> {
 }
 Minimap = <table> {
 }
 PulseCD = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 Bag = <table> {
 }
 Position = <table> {
 }
 ActionBar = <table> {
 }
 Automation = <table> {
 }
 Cooldown = <table> {
 }
 Error = <table> {
 }
}
L = <table> {
}
_ = <table> {
}
GetAddOnInfo = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 4
(*temporary) = "Mapster"
(*temporary) = "Mapster"
(*temporary) = "attempt to index field 'map' (a nil value)"`

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/c966c3ea88dcbb10a75b52ca017b3ab448b7c02c
