### ISSUE TITLE
Chat Channel names 

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#24]
![image](https://cloud.githubusercontent.com/assets/649921/17538390/bc4048fa-5e9c-11e6-9fce-bb167e09afce.png)
Not sure if that's how you want them. but I'm imagining not.

**Comment by Kkthnx** [comment]
I don't have game time currently so I can't test this push I just made. I'm just guessing. I'll leave this open for you @AutoJames and you can let me know bud. Thank you very much for using my UI and thank you for the report.

**Comment by AutoJames** [comment]
Yup. That fixed it.

And no problem. Long time Tuk and Elv user but they became boring so I figured I'd switch to you since that's what you started with.

**Comment by Kkthnx** [comment]
Awesome. I am glad to hear it.
