### ISSUE TITLE
Unit Frames - Not able to enable health numbers all the time Only show on hover.

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#25]
Pretty much the title. Can't enable health numbers on unit frames they only show on hover.

**Comment by Kkthnx** [comment]
Have you tried the interface options? They are controlled in there. Something like Interface // StatusText??? Let me log into my level 1.

**Comment by Kkthnx** [comment]
Oh, it is bugged. Weird.

**Comment by AutoJames** [comment]
Changing the option and putting it back to "Numeric Value" fixed it. but yeah still bugged.

Could be a Blizzard though though.

**Comment by Kkthnx** [comment]
Try the latest commit @AutoJames

**Comment by Kkthnx** [comment]
I logged to see if the values would stick and not turn invisible and they stuck. Let me know.

**Comment by AutoJames** [comment]
Yup it stuck.
