### ISSUE TITLE
TargetFrameDebuff - Missing time numbers11

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#26]
I recall you used to have the actual time reminding as a number in the TargetFrameDebuffs but that may have been an addon. if it was an addon I used to use just close this.

![image](https://cloud.githubusercontent.com/assets/649921/17540142/d918bade-5eab-11e6-9118-cd227550684d.png)

**Comment by Kkthnx** [comment]
I plan to revert my cooldown stuff to the old code tomorrow. 💨
