### ISSUE TITLE
No Way to Equip a Bag

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#27]
I know you mentioned the bag feature was currently disabled in issue #6, but is there a way to equip new bags while the bag feature is disabled? I'm not seeing a way to get to the bag bar or micro menu. Great compilation btw! 

Sidenote: I plan on using your UI through legion after getting tired of Elvui. If you want, I'll report issues as I come across them.

**Comment by Kkthnx** [comment]
Damn, I don't know why I didn't think of this. I am very sorry. I test my UI on a level 2 druid on my starter account. (Currently no game time) so features like this I easily just look over. I will work on this asap. I apologize. For now, I really suggest using Bagnon with my UI.

https://mods.curse.com/addons/wow/bagnon

**Comment by Kkthnx** [comment]
Fixed in commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/cf7c913caa052550a245b169896fee5b45e88884

please test.

**Comment by BernCarney** [comment]
![image](https://cloud.githubusercontent.com/assets/18447002/17645976/3109f69e-6173-11e6-8731-073e28a54b6a.png)

No way to enable bag options. The settings groups is gone from the settings. I tried looking for the reason why but could not find anything...

**Comment by Kkthnx** [comment]
Thanks for the reply. Please reinstall the UI. Exit the game out and remove the KkthnxUI and KkthnxUI_Config. Then download the latest from here.. That should fix your issue.

**Comment by BernCarney** [comment]
I deleted both folders, removed the saved variables and no change.

**Comment by Kkthnx** [comment]
This is very weird. Let me upload a clean copy to here.

**Comment by Kkthnx** [comment]
@BernCarney Try a clean copy now. I have the option on my end and I just uploaded that version.

**Comment by BernCarney** [comment]
Not sure why that worked, but the latest push you just did fixed the option not showing.

**Comment by BernCarney** [comment]
![image](https://cloud.githubusercontent.com/assets/18447002/17646067/fb1fe6c0-6176-11e6-8d1a-3a8506e072cc.png)

Works as far as I can tell. Took me a little bit to realize you had to right click the X to get the menu but it works. May want to make a menu button next to the X or a tooltip when you open your bags for the first time.
