### ISSUE TITLE
lvl up

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI_Legion#29]
17x [ADDON_ACTION_BLOCKED] Аддон 'KkthnxUI' пытался вызвать защищенную функцию 'SecureHandlersUpdateFrame:SetAttribute()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetAttribute'
FrameXML\SecureHandlers.lua:690: in function <FrameXML\SecureHandlers.lua:677>
(tail call): ?
KkthnxUI\Modules\ActionBars\Bar1.lua:58: in function <KkthnxUI\Modules\ActionBars\Bar1.lua:54>

Locals:

**Comment by Kkthnx** [comment]
Will look into this.

**Comment by Kkthnx** [comment]
Question, what version of the UI are you on? I thought I fixed this..

**Comment by kitaro2003** [comment]
always download the latest version ====>  https://github.com/Kkthnx/KkthnxUI_Legion

**Comment by Kkthnx** [comment]
I'm sure its something silly that I am looking over. I'll get it adjusted. Sorry for the inconvenience.

**Comment by kitaro2003** [comment]
всё хорошо ! это не проблема , спасибо вам за работу ))

**Comment by Kkthnx** [comment]
This is do to the unit frames being moved on my end I think. I just need to seriously move to oUF.
