### ISSUE TITLE
Auto Accept cross realm invites don't work.

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#30]
Auto accepting of cross realm invites (Battletag friends) doesn't work. I recall this working in older versions (maybe a different UI entirely)

**Comment by Kkthnx** [comment]
Should be an easy fix. I'll work on it.

**Comment by Kkthnx** [comment]
@AutoJames Can you confirm this has been fixed?

**Comment by AutoJames** [comment]
Yup that worked.
