### ISSUE TITLE
Filger CDs overlap resource bar when > 4

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#32]
![image](https://cloud.githubusercontent.com/assets/18447002/17646145/43c32c4a-617a-11e6-9e81-79e3a64537dd.png)

Possible grow left when more than 4 cooldowns are showing or break to a new row to solve issue.

**Comment by Kkthnx** [comment]
This is gonna be hard to fix without it happening again because that resource bar is all over the place when moving around. But I will indeed work on it. Thanks @BernCarney

**Comment by BernCarney** [comment]
No worries, I'll keep opening things as I notice them and work on what I can.

**Comment by Kkthnx** [comment]
Awesome. Glad to have you using my UI. Thank you for all the reports.
