### ISSUE TITLE
iLvL displayed incorrectly on icon in bags for lower quality items

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#33]
![image](https://cloud.githubusercontent.com/assets/18447002/17646810/1fc8fad2-6197-11e6-876a-d95d3c93f39a.png)

**Comment by BernCarney** [comment]
Seems like it's only for some green items. Need more items to test since the rare i685 items are working fine.

**Comment by phx7** [comment]
Same for invasion items, lower level items has same name as 700 level and display ilvl700.

**Comment by Kkthnx** [comment]
Noted for both. Will look into it. Monday. Gonna take a break today. 💃

**Comment by Sixfiveone** [comment]
Also doing the same thing for some Baleful BoA gear as seen here: 
![image](https://cloud.githubusercontent.com/assets/21069253/17718404/b7393d2c-63e1-11e6-967b-b82cd52d11f6.png)

**Comment by Kkthnx** [comment]
Noted, Thank you to the both of you for the in-depth reports.

**Comment by BernCarney** [comment]
Does it for low level items that are warforged as well (ilvl 44 here).

![image](https://cloud.githubusercontent.com/assets/18447002/17824108/4902006c-661d-11e6-8630-5fa7f232013a.png)

**Comment by Kkthnx** [comment]
This is fixed on the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
