### ISSUE TITLE
Nameplates

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#36]
2573x ...faceKkthnxUI\Modules\Blizzard\Nameplates.lua:11: attempt to call field '?' (a nil value)
...faceKkthnxUI\Modules\Blizzard\Nameplates.lua:11: in function <...faceKkthnxUI\Modules\Blizzard\Nameplates.lua:11>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 1471232474.238
(*temporary) = "SPELL_DAMAGE"
(*temporary) = false
(*temporary) = "Vehicle-0-3024-1-22198-108658-000131369F"
(*temporary) = "Goblin Bomber"
(*temporary) = 2584
(*temporary) = 0
(*temporary) = "Creature-0-3024-1-22198-92115-00003139B2"
(*temporary) = "Fel Screecher"
(*temporary) = 2632
(*temporary) = 0
(*temporary) = 223432
(*temporary) = "Rocket Barrage"
(*temporary) = 4
(*temporary) = 9038
(*temporary) = -1
(*temporary) = 4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = "attempt to call field '?' (a nil value)"

**Comment by Kkthnx** [comment]
Can you confirm that you still get this with the latest updates to nameplates?

**Comment by Kkthnx** [comment]
@jenderle7

**Comment by jenderle7** [comment]
I have not seen this error recently. Thanks for all the updates!

**Comment by Kkthnx** [comment]
You are very very welcome @jenderle7
