### ISSUE TITLE
Status Text on Dead Target

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#40]
This may actually be a blizzard bug. Status text should be hidden when the unit is dead. Right now it shows "Dead" as well as 0% HP.

![image](https://cloud.githubusercontent.com/assets/18447002/17690398/9c689754-634b-11e6-9f7b-ba35b72a1b8a.png)

**Comment by Kkthnx** [comment]
I think I finally have this fixed locally. Will push once realms come back up.

**Comment by Sixfiveone** [comment]
Was this pushed for release? Still having this issue and I'm on 5.0.7. Also, I'd like to chat with you directly @Kkthnx - mind adding me to battlenet? Mine is Se7en#1289

**Comment by Kkthnx** [comment]
Request sent.

**Comment by Kkthnx** [comment]
Are we still having this issue? I have not ran into it.

**Comment by Epsynus** [comment]
For what it's worth I have not ran into this issue for a long time myself so it would seem to be fixed.

**Comment by Kkthnx** [comment]
Awesome. We will close this then. I might push a Stable release today. Thank you for the feedback.
