### ISSUE TITLE
Hotkeys Not Displayed w/ latest update

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#46]
![image](https://cloud.githubusercontent.com/assets/18447002/17821799/bfd804fa-6610-11e6-9d3c-e5e636caff7e.png)

**Comment by Kkthnx** [comment]
Well damn. Ill look into this.

**Comment by stevenfre** [comment]
I works now for me. Thanks for all the updates today!

**Comment by Kkthnx** [comment]
Always. :D
