### ISSUE TITLE
Casting Bar Border is only thing Showing in latest update

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#47]
![image](https://cloud.githubusercontent.com/assets/18447002/17827516/57abe09c-663b-11e6-9999-2a0980db746d.png)

**Comment by Kkthnx** [comment]
I can't reproduce this. Very weird bug you are getting.

**Comment by BernCarney** [comment]
The target casting bar works fine which is the even weirder part.

![image](https://cloud.githubusercontent.com/assets/18447002/17827762/e6f50ff4-663f-11e6-8f6a-d43a25e3db27.png)

**Comment by BernCarney** [comment]
Works fine on mage alt. 

![image](https://cloud.githubusercontent.com/assets/18447002/17827867/96b0e282-6641-11e6-9538-c961f057c298.png)

**Comment by stevenfre** [comment]
Have you checked if you have set it to Castbar Underneath Player Frame? Maybe disable the addon and see if it's checked.

**Comment by BernCarney** [comment]
I'm going to consider this fixed. The last push has the cast bars a show in the same way across all characters. Good call @stevenfre on disabling the addon to set the cast bar position as well (wasn't causing any problems).
