### ISSUE TITLE
Showing levels in raid unitframes

### ISSUE THREAD

**Issue by stevenfre** [Kkthnx/KkthnxUI_Legion#48]
Thanks for all your work. I'm still trying to learn how to use this site so bear with me.
I think if you wanna include levels in raid-unitframes you should have it disabled by default, and make a option for it. (Maybe it's already there, and I'm stupid :p)

![wowscrnshot_082016_131522](https://cloud.githubusercontent.com/assets/21105287/17830826/3e2f48be-66d8-11e6-8ca6-cac4273e3632.jpeg)

**Comment by Kkthnx** [comment]
This is still a work in progress. This is due to me adding the level to that nameplates :D
