### ISSUE TITLE
Health Bar Disappearing 

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#50]
I haven't been able to pinpoint when and why this issue occurs but it's fairly regularly and it doesn't produce an error. Reload fixes it.
![wowscrnshot_082016_141450](https://cloud.githubusercontent.com/assets/233154/17834061/27f5070a-66f6-11e6-96d3-6e995f4e81d3.jpg)

**Comment by Kkthnx** [comment]
Haven you tried clean installing the entire UI? Also try it without any other addons?

**Comment by jenderle7** [comment]
Another clean install appears to have done the trick. Thanks!
