### ISSUE TITLE
Unitframes

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#51]
7x KkthnxUI\Modules\Unitframes\Layout.lua:259: attempt to index field '?' (a nil value)
KkthnxUI\Modules\Unitframes\Layout.lua:259: in function <KkthnxUI\Modules\Unitframes\Layout.lua:44>

Locals:
self = Unitframes {
 0 = <userdata>
}
event = "ADDON_LOADED"
addon = "KkthnxUI"
(for index) = 1
(for limit) = 5
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "1"
(*temporary) = <userdata>
(*temporary) = "BOTTOMLEFT"
(*temporary) = 0
(*temporary) = 15
(*temporary) = <userdata>
(*temporary) = 200
(*temporary) = <userdata>
(*temporary) = TargetFrameTextureFrameHealthBarText {
 0 = <userdata>
}
(*temporary) = TargetFrameTextureFrameManaBarText {
 0 = <userdata>
}
(*temporary) = FocusFrameTextureFrameHealthBarText {
 0 = <userdata>
}
(*temporary) = FocusFrameTextureFrameManaBarText {
 0 = <userdata>
}
(*temporary) = PetFrameHealthBarText {
 0 = <userdata>
}
(*temporary) = PetFrameManaBarText {
 0 = <userdata>
}
(*temporary) = "attempt to index field '?' (a nil value)"
InCombatLockdown = <function> defined =[C]:-1
C = <table> {
 Misc = <table> {
 }
 General = <table> {
 }
 Media = <table> {
 }
 Blizzard = <table> {
 }
 Chat = <table> {
 }
 Loot = <table> {
 }
 Aura = <table> {
 }
 Skins = <table> {
 }
 Filger = <table> {
 }
 filger_spells = <table> {
 }
 Tooltip = <table> {
 }
 Minimap = <table> {
 }
 PulseCD = <table> {
 }
 Announcements = <table> {
 }
 Unitframe = <table> {
 }
 Bag = <table> {
 }
 Position = <table> {
 }
 ActionBar = <table> {
 }
 Automation = <table> {
 }
 Cooldown = <table> {
 }
 Error = <table> {
 }
}
hooksecurefunc = <function> defined =[C]:-1
UnitPlayerControlled = <function> defined =[C]:-1
UnitIsPlayer = <function> defined =[C]:-1
RAID_CLASS_COLORS = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 SHAMAN = <table> {
 }
 WARLOCK = <table> {
 }
 DEMONHUNTER = <table> {
 }
 DEATHKNIGHT = <table> {
 }
 DRUID = <table> {
 }
 MONK = <table> {
 }
 ROGUE = <table> {
 }
}
select = <function> defined =[C]:-1
UnitClass = <function> defined =[C]:-1
UnitIsDeadOrGhost = <function> defined =[C]:-1
UnitIsEnemy = <function> defined =[C]:-1
UnitReaction = <function> defined =[C]:-1
CUSTOM_CLASS_COLORS = nil
GetUnitName = <function> defined @FrameXML\UnitFrame.lua:972
pairs = <function> defined =[C]:-1
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Scale = <function> defined @KkthnxUI\Core\API.lua:25
 Border = <table> {
 }
 ModifyFrame = <function> defined @KkthnxUI\Core\Functions.lua:97
 Mult = 1
 White_List = <table> {
 }
 Client = "enUS"
 WoWBuild = "22423"
 WoWPatch = "7.0.3"
 ScreenWidth = 2480
 UploadDBM = <function> defined @KkthnxUI\Modules\Skins\Addons\DBM.lua:264
 MoverFrames = <table> {
 }
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:113
 PixelBorder = <table> {
 }
 StylePet = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:177
 TexCoords = <table> {
 }
 CreateBorder = <function> defined @KkthnxUI\Core\Border.lua:80
 ShiftBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:13
 VersionNumber = 5.09
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:262
 PetBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:51
 TocVersion = 70000
 NeedLoot = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "ROGUE"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "2480x1395"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:54
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:249
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:226
 TimeColors = <table> {
 }
 WoWPatchReleaseDate = "Aug 11 2016"
 Level = 95
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:164
 NoScaleMult = 0.5505376344086
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\C

**Comment by Kkthnx** [comment]
Not able to reproduce this. Not even seeing how you got this.

**Comment by jenderle7** [comment]
I have no idea either. I don't know if this is related to the health frames disappearing that I posted Friday but that issue has once again popped back up (after a clean install and no addons) I think the health frames disappearing are related to exiting a vehicle (like the siege vehicles and blade throwers from the invasion events)

**Comment by Kkthnx** [comment]
Ill try that.

**Comment by Kkthnx** [comment]
It is due to an InCombat check. I see the issue. Well not really an issue. But I'll try to work around it.

**Comment by Kkthnx** [comment]
This should be temp fixed.
