### ISSUE TITLE
Spy Addon Window Location Won't Save

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#52]
I have no idea if this is an issue with Spy itself or with the UI but ever since I did a clean install my Spy window will no longer save the location after moving and reloading. Any ideas?

**Comment by Kkthnx** [comment]
I just tested this and it works fine for me. Although the skin did an update which I just pushed. https://github.com/Kkthnx/KkthnxUI_Legion/commit/2a32483940a0767f7ff1592129f5d3b23172bea7

**Comment by jenderle7** [comment]
Okay, I'll try another install and see what happens. I figured it was probably something on my end but thanks for taking a look anyways :D
