### ISSUE TITLE
Filger Positioning Relative to Resource Display

### ISSUE THREAD

**Issue by BernCarney** [Kkthnx/KkthnxUI_Legion#53]
Found this gem on how someone is positioning their WeakAuras relative to the personal resource display and thought it would be perfect for the Filger icons as well. Not sure about implementation but would be a great addition I think.

Relevant code: SetPoint("BOTTOMLEFT",ClassNameplateManaBarFrame,-2,-27)
Frame Name: ClassNameplateManaBarFrame

https://www.reddit.com/r/wow/comments/4yz59a/_/

Gotta jet to work, will add more info as I research more when I'm back.

**Comment by Kkthnx** [comment]
This won't be possible. It will run into so many issues. So far if they frame goes away the filger icons get locked into place and don't move anymore and become a permanent icon on the Interface and no longer show a cooldown.

**Comment by BernCarney** [comment]
Oof, oh well. Seemed promising at first. Go ahead and close if it's not a proper solution.

**Comment by Kkthnx** [comment]
Will figure something out.
