### ISSUE TITLE
Stealth bar & Bag suggestion

### ISSUE THREAD

**Issue by p0tten** [Kkthnx/KkthnxUI_Legion#54]
Im not sure if this changed recently but when i use stealth it stays on the main bar and dosent switch, can i fix this somehow?

Also, is it possible to make me able to see currency in the bags?

**Comment by Kkthnx** [comment]
I fixed the stealth bar not long ago. Are you on the latest Github build? I'll test on my rogue.

**Comment by Kkthnx** [comment]
Just tested and yes it does work fine on my end on the latest Github build.

**Comment by p0tten** [comment]
Ok, now it works... weird xD Thanks for the help! Keep up the good work :)
