### ISSUE TITLE
Nameplates

### ISSUE THREAD

**Issue by p0tten** [Kkthnx/KkthnxUI_Legion#57]
Hey, could you make the "hide friendly" in the nameplates option come back? It was exactly how i wanted it and now its changed again :( Other than that, great job! Loving this UI more and more everyday.

Edit: Any chance you could add the option to show your resource on enemy nameplates? (Combo points for example)

The only way i can get this to work right now is to enable "Personal resource display" in interface settings, but i dont really like that bar underneath my character.

**Comment by Kkthnx** [comment]
Old options will be added in time. Right now I am just focusing on making this stable.

**Comment by Kkthnx** [comment]
I will keep this open as a reminder for myself.

**Comment by p0tten** [comment]
Added another suggestion in OP
