### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI_Legion#59]
3x [ADDON_ACTION_FORBIDDEN] Аддон 'KkthnxUI' пытался вызвать защищенную функцию 'ReportPlayerIsPVPAFK()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `ReportPlayerIsPVPAFK'
FrameXML\UnitPopup.lua:1786: in function `func'
FrameXML\UIDropDownMenu.lua:760: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
nil

**Comment by Kkthnx** [comment]
This is due to the poor way I handle the unit frames currently and the cast bars.
