### ISSUE TITLE
Bags option doesn't apply

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#6]
The only other thing I've noticed is the default multiple bag windows appear instead of the single window from your Option menu (no errors though) This is the extent of what I've caught so far. I'll post if I find anything else. Thanks again!

**Comment by Kkthnx** [comment]
Bags are turned off right now. This is known. I just have the code commented out.

**Comment by jenderle7** [comment]
Sorry, didn't catch that

**Comment by Kkthnx** [comment]
Hey, not a problem! Seriously thank you for posting these. I will get on them when I wake up tomorrow!

**Comment by Kkthnx** [comment]
I plan to fix this up this coming weekend. I am dreading having to do this.

**Comment by jenderle7** [comment]
No worries! I actually don't mind the default bags

**Comment by Kkthnx** [comment]
Hey! I'm slowly working on this. I have a lot of doctor appts coming up and been very busy. This is still on my list of things to get done :D

**Comment by jenderle7** [comment]
Cool! No rush here :D

**Comment by Kkthnx** [comment]
@jenderle7 Bags are implemented. Please test them and break them if possible :D

**Comment by jenderle7** [comment]
All is well so far :D

**Comment by Kkthnx** [comment]
Fixed.
