### ISSUE TITLE
Unitframe health bar issue?

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#62]
After a clean install and no addons loaded I'm still seeing the health bar disappear or display oddly (screenshot) on unitframes after exiting a vehicle during invasions (not sure if this is an issue outside of invasions/phasing). Note - not producing any errors during this
![wowscrnshot_082816_085237](https://cloud.githubusercontent.com/assets/233154/18037334/b5b8eec0-6d46-11e6-929c-e79b9476fffd.jpg)

**Comment by Kkthnx** [comment]
Okay I will look into this. I think I know why.

**Comment by Kkthnx** [comment]
It does go back to normal after a /reload right?

**Comment by jenderle7** [comment]
Yes, a reload fixes this

**Comment by Kkthnx** [comment]
Let me know how this fix goes bud! :D As always thank you for the continued support and the use of my UI and reports! You rock!

**Comment by jenderle7** [comment]
No problem at all! Appreciate the quick turn around on the issues. I did just test this on a few invasions and it did pop up again but not on a clean install. I'll try that now.

**Comment by jenderle7** [comment]
So after clean install I was able to reproduce this again but only with the "Modified Blizzard unitframes graphics with fat bar...." toggled on. When using the default unitframes I wasn't able to reproduce.

**Comment by Kkthnx** [comment]
Hmm. Will further test then.

**Comment by jenderle7** [comment]
So far so good! I think the last update did the trick but I did encounter another small issue when entering a vehicle. Occasionally the fat bar will apply like so...
![wowscrnshot_082816_204035](https://cloud.githubusercontent.com/assets/233154/18038937/5466c9c2-6d63-11e6-90fa-345e18f82dfb.jpg)
