### ISSUE TITLE
iLvl wrong on character sheet

### ISSUE THREAD

**Issue by AutoJames** [Kkthnx/KkthnxUI_Legion#63]
![image](https://cloud.githubusercontent.com/assets/649921/18201490/67eb1ff0-7102-11e6-940a-2c8896890269.png)
![image](https://cloud.githubusercontent.com/assets/649921/18201517/8dadea1a-7102-11e6-8bc3-41e6f794651f.png)

**Comment by Kkthnx** [comment]
This is actively being worked on.

**Comment by Kkthnx** [comment]
Still actively being worked on. It has been improved a number of times now.

**Comment by Kkthnx** [comment]
This is fixed on the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
