### ISSUE TITLE
Tooltip Bug on World Quests

### ISSUE THREAD

**Issue by p0tten** [Kkthnx/KkthnxUI_Legion#64]
Getting this weird tooltip bug on some of the world quests

![wowscrnshot_090216_200534](https://cloud.githubusercontent.com/assets/21223941/18213658/9a890336-7149-11e6-93ef-c950e9d6145c.jpg)

**Comment by Kkthnx** [comment]
I haven't hit 110 yet but I think I know the issue here.

**Comment by Epsynus** [comment]
To provide an update. The latest commit would seem to have resolved this issue, have not encountered it with any of my world quests since then! Thanks :+1:

**Comment by Kkthnx** [comment]
You are welcome 💨
