### ISSUE TITLE
BigDebuffs 

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI_Legion#66]
The bug had appeared since the last update KkthnxUI . In the old version of this error is not.Please correct. If possible =) 
BigDebuffs I love to use it.
Thank you for your excellent work!

3x BigDebuffs\BigDebuffs-v4.9.lua:670: Usage: RawHook([object], method, [handler], [hookSecure]): 'object' - nil or table expected got boolean
[C]: ?
...eBigDebuffs\libs\AceHook-3.0\AceHook-3.0-8.lua:130: in function <...eBigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:118>
...eBigDebuffs\libs\AceHook-3.0\AceHook-3.0-8.lua:322: in function `RawHook'
BigDebuffs\BigDebuffs-v4.9.lua:670: in function <BigDebuffs\BigDebuffs.lua:659>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:995: in function <FrameXML\UIParent.lua:891>

Locals:
nil

**Comment by Kkthnx** [comment]
Try the latest build on GitHub and let me know if this workaround works :D

**Comment by kitaro2003** [comment]
Thank you! No error! :+1:  :dancer:
