### ISSUE TITLE
Minimap Button Errors

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#7]
6x ...s\KkthnxUI\Modules\Skins\Blizzard\MinimapButtons.lua:39: attempt to index local 'tex' (a number value)
...s\KkthnxUI\Modules\Skins\Blizzard\MinimapButtons.lua:39: in function <...s\KkthnxUI\Modules\Skins\Blizzard\MinimapButtons.lua:20>
...s\KkthnxUI\Modules\Skins\Blizzard\MinimapButtons.lua:64: in function <...s\KkthnxUI\Modules\Skins\Blizzard\MinimapButtons.lua:61>

Locals:
f = LibDBIcon10_Rarity {
 0 = <userdata>
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = <unnamed> {
 }
}
(for index) = 3
(for limit) = 3
(for step) = 1
i = 3
region = <unnamed> {
 0 = <userdata>
 UpdateCoord = <function> defined @BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:153
}
tex = 134337
(*temporary) = <unnamed> {
 0 = <userdata>
 UpdateCoord = <function> defined @BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:153
}
(*temporary) = 134337
(*temporary) = <unnamed> {
 0 = <userdata>
 UpdateCoord = <function> defined @BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:153
}
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <unnamed> {
 0 = <userdata>
 UpdateCoord = <function> defined @BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:153
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tex' (a number value)"
buttons = <table> {
 1 = "QueueStatusMinimapButton"
 2 = "MiniMapTrackingButton"
 3 = "MiniMapMailFrame"
 4 = "HelpOpenTicketButton"
 5 = "GatherMatePin"
 6 = "HandyNotesPin"
 7 = "TimeManagerClockButton"
}
select = <function> defined =[C]:-1
K = <unnamed> {
 0 = <userdata>
 ShadowBackdrop = <table> {
 }
 SetFontString = <function> defined @KkthnxUI\Core\Functions.lua:36
 Comma = <function> defined @KkthnxUI\Core\Functions.lua:46
 Border = <table> {
 }
 Unit = "Player-163-08A86FF4"
 Mult = 0.83333333333333
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:52
 White_List = <table> {
 }
 Client = "enUS"
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:11
 WoWBuild = "22293"
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:116
 WoWPatch = "7.0.3"
 TexCoords = <table> {
 }
 ScreenWidth = 2560
 StylePet = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:150
 MoverFrames = <table> {
 }
 CheckChat = <function> defined @KkthnxUI\Core\Functions.lua:98
 PixelBorder = <table> {
 }
 UIFrameFadeRemoveFrame = <function> defined @KkthnxUI\Core\Animation.lua:128
 ShiftBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:5
 UIFrameFadeOut = <function> defined @KkthnxUI\Core\Animation.lua:107
 CreateBorder = <function> defined @KkthnxUI\Core\Border.lua:80
 VersionNumber = 4.08
 Delay = <function> defined @KkthnxUI\Core\Functions.lua:247
 PetBarUpdate = <function> defined @KkthnxUI\Modules\ActionBars\Functions.lua:43
 TocVersion = 70000
 NeedLoot = <table> {
 }
 BorderBackdrop = <table> {
 }
 Black_List = <table> {
 }
 Color = <table> {
 }
 Class = "WARRIOR"
 Print = <function> defined @KkthnxUI\Core\Functions.lua:32
 Resolution = "2560x1440"
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:67
 Role = "Melee"
 UIFrameFadeIn = <function> defined @KkthnxUI\Core\Animation.lua:97
 FormatMoney = <function> defined @KkthnxUI\Core\Functions.lua:234
 WoWPatchReleaseDate = "Jul 22 2016"
 Level = 100
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:149
 NoScaleMult = 0.53333333333333
 TimeFormats = <table> {
 }
 RGBToHex = <function> defined @KkthnxUI\Core\Functions.lua:90
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:211
 TimeColors = <table> {
 }
 ComboColor = <table> {
 }
 RuneColor = <table> {
 }
 Backdrop = <table> {
 }
 UIParent = KkthnxUIParent {
 }
 Round = <function> defined @KkthnxUI\Core\Functions.lua:81
 ScreenHeight = 1440
 Version = "4.08"
 Noop = <function> defined @KkthnxUI\Core\Init.lua:13
 Race = "Gnome"
 StyleShift = <function> defined @KkthnxUI\Modules\ActionBars\Style.lua:140
 Realm = "The Venture Co"
 Name = "Frackas"
}
unpack = <function> defined =[C]:-1
C = <table> {
 Nameplate = <table> {

**Comment by Kkthnx** [comment]
Should be fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/442ca53987f93d1baf463e9416134ff0f21ac645
