### ISSUE TITLE
Actionbar Issue

### ISSUE THREAD

**Issue by HolyAkiao** [Kkthnx/KkthnxUI_Legion#71]
Hi mate

For some reason in your settings menu it doesn't matter if I choose 1,2 or 3 bars down the bottom showing, It only ever shows 3. Not sure if this is a bug or I'm missing something.

**Comment by Kkthnx** [comment]
Please watch both of these.

http://i.imgur.com/eumJewb.gif
http://i.imgur.com/uG9e6sM.gif
