### ISSUE TITLE
nameplateKAI

### ISSUE THREAD

**Issue by vortex250** [Kkthnx/KkthnxUI_Legion#72]
Author, your UI is about as perfect as it gets, i've recommended it to many people.
the only thing i dont like is the nameplates, which i use nameplateKAI instead, the theme of the 2 addons seem to match perfectly, which i believe is your goal, i think you should absorb the code into your own since it has color filtering etc.

food for thought.

**Comment by Kkthnx** [comment]
Thank you! Sorry for the late reply. Very busy here lately. As always I take all suggestion into consideration.

**Comment by Kkthnx** [comment]
Nameplates were already redone and being improved upon as much as possible.
