### ISSUE TITLE
Major lag when sorting bags

### ISSUE THREAD

**Issue by skywalkerRCP** [Kkthnx/KkthnxUI_Legion#74]
Not sure what happened with recent updates but now when sorting bags there is some major lag. Only started about a week ago.

**Comment by Kkthnx** [comment]
What option are you using?

**Comment by Kkthnx** [comment]
No matter what I am looking into this. Thank you.

**Comment by Kkthnx** [comment]
Can you please confirm with the latest GitHub build, that this is now fixed for Sorting Blizzard option? @skywalkerRCP

**Comment by Kkthnx** [comment]
This is fixed on the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
