### ISSUE TITLE
Cant open bank

### ISSUE THREAD

**Issue by p0tten** [Kkthnx/KkthnxUI_Legion#75]
For some reason, after the latest update i cant open my bank anymore.

If i disable the UI or the "Enable bags" option it works.

No lua error or anything shows up.

**Comment by Sixfiveone** [comment]
I second having this issue. I'm on a 100% fresh install with no other addons installed.

**Comment by Kkthnx** [comment]
Latest Github version?

**Comment by Kkthnx** [comment]
I'm working on an lag issue with sorting on the bags so this would be why :D

**Comment by Sixfiveone** [comment]
Yea mine is the latest GitHub version.

**Comment by p0tten** [comment]
Any updates on this soon?

**Comment by Kkthnx** [comment]
It is fixed in the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta

**Comment by p0tten** [comment]
> It is fixed in the beta.

> https://github.com/Kkthnx/KkthnxUI_Legion_Beta

Great, Thanks!
