### ISSUE TITLE
specific abillities causes 1~ second game freeze

### ISSUE THREAD

**Issue by thalashye** [Kkthnx/KkthnxUI_Legion#76]
bloodthirst/rampage specifically freezes my game for 0.5-1 seconds each time i use them, this happened after updating kkthnxui on curse client today (27/09/2016)

**Comment by Kkthnx** [comment]
IM going to say this is Filger causing this with something I changed. Try disabling this module and let me know.

**Comment by thalashye** [comment]
Did not fix it unfortunately :/

**Comment by Kkthnx** [comment]
The best thing to do here is to disable 1 thing after another. Nameplates, Filger, action bars etc etc... This way you can help figure out what is causing the issue for you and this way I have better idea.

**Comment by Kkthnx** [comment]
@thalashye Try turning off the combat text module. I noticed an fps increase with this off. Let me know.

**Comment by Kkthnx** [comment]
This is fixed on the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
