### ISSUE TITLE
unable to join random PVP battleground

### ISSUE THREAD

**Issue by nmeitas** [Kkthnx/KkthnxUI_Legion#77]
trying to join a random battlegrounds throws following error:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'KkthnxUI' tried to call the protected function 'JoinBattlefield()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:551: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by Kkthnx** [comment]
Just relog your UI. I already fixed this in my 6.0 release.
