### ISSUE TITLE
Item Preview Error

### ISSUE THREAD

**Issue by Xaski** [Kkthnx/KkthnxUI_Legion#78]
Hello, 

Awesome UI! Been using it now for a few weeks, today I notice when I was trying to preview an item from a PVP vendor that I kept getting the below error. Not sure if this is an issue with the UI, but I know I was able to preview items before setting things up. 

I can preview the items once I buy them so it it seems related to item merchants have only. 

Message: [string "MerchantItem10ItemButton:OnClick"]:2: attempt to call global 'MerchantItemButton_OnModifiedClick' (a nil value)
Time: 10/04/16 14:31:32
Count: 2
Stack: [string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: self = MerchantItem10ItemButton {
 0 = <userdata>
 hasItem = true
 UpdateTooltip = <function> defined @Interface\FrameXML\MerchantFrame.lua:509
 numInStock = -1
 count = 1
 texture = 875845
 extendedCost = true
 link = "[Grievous Gladiator's Reprieve]"
 name = "Grievous Gladiator's Reprieve"
 Count = MerchantItem10ItemButtonCount {
 }
 IconBorder = <unnamed> {
 }
 showNonrefundablePrompt = false
 searchOverlay = MerchantItem10ItemButtonSearchOverlay {
 }
 icon = MerchantItem10ItemButtonIconTexture {
 }
 SplitStack = <function> defined @Interface\FrameXML\MerchantFrame.lua:421
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = MerchantItem10ItemButton {
 0 = <userdata>
 hasItem = true
 UpdateTooltip = <function> defined @Interface\FrameXML\MerchantFrame.lua:509
 numInStock = -1
 count = 1
 texture = 875845
 extendedCost = true
 link = "[Grievous Gladiator's Reprieve]"
 name = "Grievous Gladiator's Reprieve"
 Count = MerchantItem10ItemButtonCount {
 }
 IconBorder = <unnamed> {
 }
 showNonrefundablePrompt = false
 searchOverlay = MerchantItem10ItemButtonSearchOverlay {
 }
 icon = MerchantItem10ItemButtonIconTexture {
 }
 SplitStack = <function> defined @Interface\FrameXML\MerchantFrame.lua:421
}
(*temporary) = "LeftButton"
(*temporary) = "attempt to call global 'MerchantItemButton_OnModifiedClick' (a nil value)"

Thanks!

Allen AKA Xaski

**Comment by Kkthnx** [comment]
This is fixed on the beta version.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
