### ISSUE TITLE
Target Frame

### ISSUE THREAD

**Issue by doozer667** [Kkthnx/KkthnxUI_Legion#80]
For at least a week I've had an issue in which the target frame would no longer function properly, showing me the names of other enemies i had targetted 5 minutes ago and showing inaccurate health totals/bars.

**Comment by Kkthnx** [comment]
Hello, Thanks for the report. This is already fixed in my more advanced beta build 🗡 

https://github.com/Kkthnx/KkthnxUI_Legion_Beta
