### ISSUE TITLE
Target Frame Issue

### ISSUE THREAD

**Issue by jenderle7** [Kkthnx/KkthnxUI_Legion#9]
I've been seeing this error for the last few days. The target unitframe disappears/turns into a green rectangle. It's rather sporadic and only happens with certain targets.

![wowscrnshot_072516_090621](https://cloud.githubusercontent.com/assets/233154/17108253/8e91da06-5247-11e6-9833-77719d494741.jpg)

2x [ADDON_ACTION_BLOCKED] AddOn 'KkthnxUI' tried to call the protected function 'TargetFrameToT:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\TargetFrame.lua:978: in function `TargetofTarget_Update'
FrameXML\TargetFrame.lua:466: in function `TargetFrame_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:

**Comment by Kkthnx** [comment]
Oh god, I completely overlooked this :( I think I know what the issue might be.

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_Legion/commit/7512751248d05049f0d56db3186ffd8834611eaf

**Comment by jenderle7** [comment]
Thanks! :D

**Comment by Kkthnx** [comment]
You are very welcome! Thank you for using my UI :D
