### ISSUE TITLE
When an item notification appears at the top, clicking on it will cause a Lua Error

### ISSUE THREAD

**Issue by FaceToKeyboard** [Kkthnx/KkthnxUI_Legion#90]
I receive a Lua error when clicking on the "notification" at the top of the game window, which occurs when receiving equipment.

![luaerror](https://cloud.githubusercontent.com/assets/4070195/19877627/5783a22a-9fb7-11e6-96df-04c5fa761c05.jpg)

**Comment by Kyman81** [comment]
![wowscrnshot_121916_125726](https://cloud.githubusercontent.com/assets/24628925/21303832/713b267a-c5eb-11e6-8c7e-88dd92bf3a20.jpg)
6.11.3

**Comment by Kkthnx** [comment]
Can you confirm the fix I just pushed?

**Comment by Kkthnx** [comment]
@Kyman81 Can you also look and translate lines 9-27

https://github.com/Kkthnx/KkthnxUI_Legion/blob/master/KkthnxUI/Locales/ruRU.lua#L9

**Comment by Kkthnx** [comment]
Fixed.
