### ISSUE TITLE
Need Russian (ruRU) translation

### ISSUE THREAD

**Issue by Kkthnx** [Kkthnx/KkthnxUI_Legion#91]
Anyone who can translate for us we would be so thankful for this.
We are in need of  Russian (ruRU) translation currently. Thank you.
I will ping 2 people to see if they can commit some free time of theirs.

@Bunny67 @freesay
If either one of you can translate these 2 files I would be forever in your debt.

Translated
Любой, кто может переводить для нас, мы были бы очень благодарны за это.
Мы нуждаемся в России (RURU) перевод в настоящее время. Спасибо.
Я пропингует 2-х человек, чтобы увидеть, если они могут совершить некоторое свободное время их.

@Bunny67 @freesay
Если какая-либо из вас может перевести эти 2 файла я был бы навсегда в вашей задолженности.

https://github.com/Kkthnx/KkthnxUI_Legion/blob/master/KkthnxUI/Locales/ruRU.lua

https://github.com/Kkthnx/KkthnxUI_Legion/blob/master/KkthnxUI_Config/Locales/ruRU.lua

**Comment by freesay** [comment]
I translated, but there may be inaccuracies, because I do not have the client Legion.
Update it for wotlk =)
